url: "http://www.andrewbr.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

title: Andrew Brandon
description: >
  Andrew Brandon: Software developer and musician

email: theman@andrewbr.com
github_username:  drbr
twitter_username: drbr153

markdown: kramdown
timezone: America/Los_Angeles
